num= input("Enter a number: \n")
num=int(num)
print(f"Table of {num} is: ")

print(f'{num} X 1 = {num*1}')
print(f'{num} X 2 = {num*1}')
print(f'{num} X 3 = {num*1}')
print(f'{num} X 4 = {num*1}')
print(f'{num} X 5 = {num*1}')
print(f'{num} X 6 = {num*1}')
print(f'{num} X 7 = {num*1}')
print(f'{num} X 8 = {num*1}')
print(f'{num} X 9 = {num*1}')
print(f'{num} X 10 = {num*1}')